# -*- coding: utf-8 -*-
"""meu_primeiro_codigo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZD4Vq7GzuWga3w_kNyLJBJerkeemunrP
"""

print('Olá Mundo!')
#isto é um comentario
'''
isto é comentário de linhas múltiplas
'''
print('Outra mensagem')

#Declarando a codificação utf8 para reconhecer caracteres, acentuação etc
# -*- coding: utf-8 -*-