# -*- coding: utf-8 -*-
"""operações matemáticas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uPi0yEJK6dKX5t8zMA4YQBIs-eworZVd
"""

# -*- coding: uft-8 -*-
print(2+2)
print(5-3)
print(12/6)
print(10*10)

# exponenciação
print(2**3) # 2 elevado a 3

#operação de módulo
print(10 / 3)
print(10 % 3)# módulo: o resto de uma operação